service: omni-dw-salesforce-datasync

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  tags: ${self:custom.tags}
  stackTags: ${self:custom.tags}
  memorySize: 128
  timeout: 30
  role: ${ssm:/omni-dw/${self:provider.stage}/lambda/role}
  environment:
    REGION: ${self:custom.region}
    STAGE: ${self:custom.stage}

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  tags:
    Application: OmniSalesforceApis
    CreateBy: BizCloudExperts
    Environment: ${self:custom.stage}

plugins:
  - serverless-offline
  - serverless-step-functions

package:
  individually: true

layers:
  OmniSalesforceDatasyncLayer:
    path: lambdaLayer/lib
    name: ${self:service}-datasync-layer-${self:provider.stage}
    description: Omni salesforce lambda layer for all node modules - ${self:provider.stage}
    compatibleRuntimes:
      - nodejs14.x
    retain: false

functions:
  fetchLatestRecordsToS3: ${file(config/functions/fetchLatestRecordsToS3.yaml):function}
  processS3Object: ${file(config/functions/processS3Object.yaml):function}
  processCsvRecord: ${file(config/functions/processCsvRecord.yaml):function}
  # processFailedRecords: ${file(config/functions/processFailedRecords.yaml):function}
  archiveFile: ${file(config/functions/archiveFile.yaml):function}

stepFunctions:
  stateMachines:
    salesforce-datasync: ${file(config/stepFunctions/salesforceDatasyncStateMachine.yaml):stateMachine}

resources:
  Resources:
    datasyncTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: salesforce-datasync-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    stateMachineRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: salesforce-datasync-stepfuction-role-${self:provider.stage}
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
        Policies:
          - PolicyName: statePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - s3:*
                    - s3-object-lambda:*
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - states:RedriveExecution
                    - states:StartExecution
                    - states:DescribeExecution
                    - states:StopExecution
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - events:PutTargets
                    - events:PutRule
                    - events:DescribeRule
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - xray:PutTraceSegments
                    - xray:PutTelemetryRecords
                    - xray:GetSamplingRules
                    - xray:GetSamplingTargets
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
    
    ArchiveFileMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: "/aws/lambda/omni-dw-salesforce-datasync-sf-archive-file-${self:provider.stage}"
        FilterPattern: "{$.status = 500}"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: "MyNamespace"
            MetricName: "sf-archive-file-error-metric-${self:provider.stage}"
    ArchiveFileAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: omni-dw-salesforce-datasync-sf-archive-file-error-alarm-${self:provider.stage}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        MetricName: sf-archive-file-error-metric-${self:provider.stage}
        Namespace: MyNamespace
        Period: 60
        Statistic: Sum
        Threshold: 1
        ActionsEnabled: true
        AlarmActions:
          - Ref: SNSTopic

    FetchLatestRecordsToS3MetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: "/aws/lambda/omni-dw-salesforce-datasync-sf-fetch-latest-records-to-s3-${self:provider.stage}"
        FilterPattern: "{$.status = 500}"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: "MyNamespace"
            MetricName: "sf-fetch-latest-records-to-s3-error-metric-${self:provider.stage}"
    FetchLatestRecordsToS3Alarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: omni-dw-salesforce-datasync-sf-fetch-latest-records-to-s3-error-alarm-${self:provider.stage}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        MetricName: sf-fetch-latest-records-to-s3-error-metric-${self:provider.stage}
        Namespace: MyNamespace
        Period: 60
        Statistic: Sum
        Threshold: 1
        ActionsEnabled: true
        AlarmActions:
          - Ref: SNSTopic

    processCsvRecordMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: "/aws/lambda/omni-dw-salesforce-datasync-sf-process-csv-record-${self:provider.stage}"
        FilterPattern: "{$.status = 500}"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: "MyNamespace"
            MetricName: "sf-process-csv-record-error-metric-${self:provider.stage}"
    processCsvRecordAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: omni-dw-salesforce-datasync-sf-process-csv-record-error-alarm-${self:provider.stage}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        MetricName: sf-process-csv-record-error-metric-${self:provider.stage}
        Namespace: MyNamespace
        Period: 60
        Statistic: Sum
        Threshold: 1
        ActionsEnabled: true
        AlarmActions:
          - Ref: SNSTopic

    processS3ObjectMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: "/aws/lambda/omni-dw-salesforce-datasync-sf-process-s3-object-${self:provider.stage}"
        FilterPattern: "{$.status = 500}"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: "MyNamespace"
            MetricName: "sf-process-s3-object-error-metric-${self:provider.stage}"
    processS3ObjectAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: omni-dw-salesforce-datasync-sf-process-s3-object-error-alarm-${self:provider.stage}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        MetricName: sf-process-s3-object-error-metric-${self:provider.stage}
        Namespace: MyNamespace
        Period: 60
        Statistic: Sum
        Threshold: 1
        ActionsEnabled: true
        AlarmActions:
          - Ref: SNSTopic
        
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "omni-dw-salesforce-error-notification-topic-${self:provider.stage}"
        TopicName: "omni-dw-salesforce-error-notification-topic-${self:provider.stage}"
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        TopicArn:
          Ref: SNSTopic
        Endpoint: ${ssm:/omni/support/${self:provider.stage}/alarm/email}