---
function:
  handler: src/archiveFile/index.handler
  memorySize: 256
  timeout: 30
  runtime: nodejs18.x
  description: omni dw salesforce sf - archive file - ${self:provider.stage}
  name: omni-dw-salesforce-datasync-sf-archive-file-${self:provider.stage}
  layers:
    - { Ref: OmniSalesforceDatasyncLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/archiveFile/**"
      - "src/shared/**"
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  environment:
    S3_BUCKET_NAME: ${ssm:/omni-dw/salesforce/${self:provider.stage}/s3/bucket-name~true}
    TOKEN_BASE_URL: ${ssm:/omni-dw/salesforce/${self:provider.stage}/baseUrl/token}
