---
function:
  handler: src/fetchLatestRecordsToS3/index.handler
  memorySize: 256
  timeout: 900
  runtime: nodejs18.x
  description: omni dw salesforce sf - fetch latest records to s3 - ${self:provider.stage}
  name: omni-dw-salesforce-datasync-sf-fetch-latest-records-to-s3-${self:provider.stage}
  layers:
    - { Ref: OmniSalesforceDatasyncLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/fetchLatestRecordsToS3/**"
      - "src/shared/**"
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  environment:
    TIMESTAMP_SSM_PARAMETER: /omni-dw/salesforce/${self:provider.stage}/db/tables/latest/timestamp
    S3_BUCKET_NAME: ${ssm:/omni-dw/salesforce/${self:provider.stage}/s3/bucket-name~true}
    DB_PORT: ${ssm:/omni-dw/salesforce/${self:provider.stage}/db/port}
    DB_HOST: ${ssm:/omni-dw/salesforce/${self:provider.stage}/db/host~true}
    DB_PASSWORD: ${ssm:/omni-dw/${self:provider.stage}/db/password.unparsed~true}
    DB_DATABASE: ${ssm:/omni-dw/salesforce/${self:provider.stage}/db/name~true}
    DB_USER: ${ssm:/omni-dw/salesforce/${self:provider.stage}/db/user~true}
    DATASYNC_DYNAMO_TABLE_NAME: !Ref datasyncTable
    REGION: ${self:provider.region}
    SERVICE: ${self:service}
