---
function:
  handler: src/sendReports/index.handler
  memorySize: 256
  timeout: 900
  runtime: nodejs18.x
  description: omni dw salesforce sf - send Reports - ${self:provider.stage}
  name: omni-dw-salesforce-datasync-sf-send-reports-${self:provider.stage}
  layers:
    - { Ref: OmniSalesforceDatasyncLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/sendReports/**"
      - "src/shared/**"
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  environment:
    REGION: ${self:provider.region}
    SERVICE: ${self:service}
    SNS_TOPIC_ARN_FAILURE: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    SNS_TOPIC_ARN_SUCCESS: ${ssm:/omni-reports/${self:provider.stage}/success-notification/sns/arn}
